"""Add clients table with enums

Revision ID: f774110e9d18
Revises: 04a0044a7091
Create Date: 2025-10-30 12:10:08.586418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f774110e9d18'
down_revision = '04a0044a7091'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('honorarios_mensais', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('regime_tributario', postgresql.ENUM('SIMPLES_NACIONAL', 'LUCRO_PRESUMIDO', 'LUCRO_REAL', 'MEI', name='regime_tributario'), nullable=False),
    sa.Column('tipo_empresa', postgresql.ENUM('COMERCIO', 'SERVICO', 'INDUSTRIA', 'MISTO', name='tipo_empresa'), nullable=False),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('responsavel_nome', sa.String(length=255), nullable=True),
    sa.Column('responsavel_cpf', sa.String(length=14), nullable=True),
    sa.Column('responsavel_email', sa.String(length=255), nullable=True),
    sa.Column('responsavel_telefone', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('ATIVO', 'INATIVO', 'PENDENTE', name='client_status'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_cnpj'), 'clients', ['cnpj'], unique=True)
    op.create_index(op.f('ix_clients_razao_social'), 'clients', ['razao_social'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_razao_social'), table_name='clients')
    op.drop_index(op.f('ix_clients_cnpj'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
